name: ae-poc-identity
services:
  identity-ui-webasm:
    image: identity-ui-webasm:v1.0.3
    container_name: ae-poc-identity-ui-webasm
    build:
      context: .
      dockerfile: ae-poc-identity-ui-webasm/Dockerfile
    ports:
      - "8080:80"
