services:
  identity-ui:
    image: identity-ui-webasm
    container_name: ae-poc-identity-ui-webasm
    build:
      context: .
      dockerfile: ae-poc-identity-ui-webasm/Dockerfile
    ports:
      - "8080:80"
    restart: always
